'use client'

import { Bot, Lock, RefreshCw, Sparkles } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { AppShell } from '@/components/app-shell'
import { ProductCards } from '@/components/product-cards'
import { usePatientData } from '@/components/use-patient-data'
import { fetchAiProducts } from '@/lib/api'
import { getRecommendedProducts } from '@/lib/experience'
import type { AIProvider, ProductRecommendation, SkinType } from '@/lib/types'

type SortBy = 'rating' | 'price-low' | 'price-high'
type SponsorFilter = 'all' | 'sponsored' | 'organic'

const SKIN_TYPES: SkinType[] = ['oily', 'dry', 'sensitive', 'combination']

const AI_PROVIDERS: { value: AIProvider; label: string }[] = [
  { value: 'gemini',      label: 'Gemini' },
  { value: 'groq',        label: 'Groq' },
  { value: 'cohere',      label: 'Cohere' },
  { value: 'openrouter',  label: 'OpenRouter' },
]

export default function ProductsPage() {
  const { user, loading, latestScan, preferences, subscription } = usePatientData()

  const [sortBy, setSortBy]               = useState<SortBy>('rating')
  const [skinType, setSkinType]           = useState<SkinType | 'current'>('current')
  const [sponsorFilter, setSponsorFilter] = useState<SponsorFilter>('all')
  const [provider, setProvider]           = useState<AIProvider>('gemini')

  const [aiProducts, setAiProducts] = useState<{
    sponsored: ProductRecommendation[]
    organic: ProductRecommendation[]
    all: ProductRecommendation[]
  } | null>(null)
  const [aiLoading, setAiLoading]   = useState(false)
  const [aiSource, setAiSource]     = useState<'ai' | 'static'>('static')

  const effectiveSkinType = skinType === 'current' ? (preferences?.skinType ?? 'combination') : skinType as SkinType

  const fetchProducts = useCallback(async () => {
    if (!preferences) return
    setAiLoading(true)
    const result = await fetchAiProducts(
      latestScan?.acne_type ?? null,
      latestScan?.severity  ?? null,
      effectiveSkinType,
      [],
      provider,
    )
    if (result.all.length > 0) {
      setAiProducts(result)
      setAiSource('ai')
    } else {
      setAiProducts(null)
      setAiSource('static')
    }
    setAiLoading(false)
  }, [latestScan, effectiveSkinType, provider, preferences])

  useEffect(() => {
    if (!loading && preferences) fetchProducts()
  }, [loading, preferences, fetchProducts])

  // derive displayed list
  const baseAll: ProductRecommendation[] = (() => {
    if (aiProducts) return aiProducts.all
    if (!preferences) return []
    return getRecommendedProducts(latestScan, effectiveSkinType, preferences.ingredientBlacklist).all
  })()

  const filtered = (() => {
    let list = baseAll
    if (sponsorFilter === 'sponsored') list = list.filter((p) => p.sponsored)
    if (sponsorFilter === 'organic')   list = list.filter((p) => !p.sponsored)
    return [...list].sort((a, b) => {
      if (sortBy === 'price-low')  return a.price - b.price
      if (sortBy === 'price-high') return b.price - a.price
      return b.rating - a.rating
    })
  })()

  if (loading || !user || !preferences || !subscription) {
    return (
      <main className="page-shell auth-shell">
        <div className="skeleton skeleton-title" style={{ width: '180px' }} />
      </main>
    )
  }

  return (
    <AppShell eyebrow="Shop smarter" title="Products">
      <section className="feature-section">
        <div className="section-heading-row">
          <div>
            <div className="section-label">Recommendations</div>
            <h2 className="section-title">AI-generated skincare picks</h2>
            <p className="muted-copy" style={{ maxWidth: '620px' }}>
              {aiSource === 'ai'
                ? 'Live recommendations generated by AI based on your latest scan and skin type.'
                : 'Showing curated picks — AI recommendations will load shortly.'}
            </p>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.5rem' }}>
            {!subscription.canUseDiscountCodes ? (
              <span className="pro-badge"><Lock size={10} /> PRO codes locked</span>
            ) : (
              <span className="pro-badge" style={{ borderColor: 'var(--success)', color: 'var(--success)' }}>
                <Sparkles size={10} /> Pro codes active
              </span>
            )}
            {aiSource === 'ai' && (
              <span className="mini-badge accent" style={{ display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                <Bot size={11} /> AI-generated
              </span>
            )}
          </div>
        </div>

        <div className="toolbar-row">
          <label className="field-stack">
            <span className="field-label">Sort by</span>
            <select className="text-select" value={sortBy} onChange={(e) => setSortBy(e.target.value as SortBy)}>
              <option value="rating">Rating</option>
              <option value="price-low">Price: Low to High</option>
              <option value="price-high">Price: High to Low</option>
            </select>
          </label>

          <label className="field-stack">
            <span className="field-label">Skin type</span>
            <select className="text-select" value={skinType} onChange={(e) => setSkinType(e.target.value as SkinType | 'current')}>
              <option value="current">My skin type ({preferences.skinType})</option>
              {SKIN_TYPES.map((type) => (
                <option key={type} value={type}>{type.charAt(0).toUpperCase() + type.slice(1)}</option>
              ))}
            </select>
          </label>

          <label className="field-stack">
            <span className="field-label">Category</span>
            <select className="text-select" value={sponsorFilter} onChange={(e) => setSponsorFilter(e.target.value as SponsorFilter)}>
              <option value="all">All products</option>
              <option value="sponsored">Sponsored only</option>
              <option value="organic">Organic only</option>
            </select>
          </label>

          <label className="field-stack">
            <span className="field-label">AI provider</span>
            <select className="text-select" value={provider} onChange={(e) => setProvider(e.target.value as AIProvider)}>
              {AI_PROVIDERS.map((p) => (
                <option key={p.value} value={p.value}>{p.label}</option>
              ))}
            </select>
          </label>

          <div className="field-stack" style={{ justifyContent: 'flex-end' }}>
            <span className="field-label">&nbsp;</span>
            <button
              type="button"
              className="button-secondary"
              onClick={fetchProducts}
              disabled={aiLoading}
              style={{ minHeight: '38px' }}
            >
              <RefreshCw size={14} style={aiLoading ? { animation: 'spin 1s linear infinite' } : undefined} />
              <span>{aiLoading ? 'Generating…' : 'Regenerate'}</span>
            </button>
          </div>
        </div>

        {aiLoading ? (
          <div className="stack" style={{ gap: '1rem' }}>
            {[1, 2, 3].map((i) => (
              <div key={i} className="skeleton" style={{ height: '160px', borderRadius: '12px' }} />
            ))}
          </div>
        ) : (
          <ProductCards products={filtered} canUseDiscountCodes={subscription.canUseDiscountCodes} />
        )}
      </section>
    </AppShell>
  )
}
