'use client'

import { Bot, RefreshCw } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { AppShell } from '@/components/app-shell'
import { RemedyCards } from '@/components/remedy-cards'
import { usePatientData } from '@/components/use-patient-data'
import { fetchAiRemedies } from '@/lib/api'
import { getHomeRemedies } from '@/lib/experience'
import type { AIProvider, HomeRemedy, SkinType } from '@/lib/types'

const SKIN_TYPES: SkinType[] = ['oily', 'dry', 'sensitive', 'combination']

const AI_PROVIDERS: { value: AIProvider; label: string }[] = [
  { value: 'gemini',      label: 'Gemini' },
  { value: 'groq',        label: 'Groq' },
  { value: 'cohere',      label: 'Cohere' },
  { value: 'openrouter',  label: 'OpenRouter' },
]

export default function RemediesPage() {
  const { user, loading, latestScan, preferences } = usePatientData()

  const [skinTypeOverride, setSkinTypeOverride] = useState<SkinType | 'current'>('current')
  const [provider, setProvider]                 = useState<AIProvider>('gemini')
  const [aiRemedies, setAiRemedies]             = useState<HomeRemedy[] | null>(null)
  const [aiLoading, setAiLoading]               = useState(false)
  const [aiSource, setAiSource]                 = useState<'ai' | 'static'>('static')

  const effectiveSkinType: SkinType = skinTypeOverride === 'current'
    ? (preferences?.skinType ?? 'combination')
    : skinTypeOverride as SkinType

  const fetchRemedies = useCallback(async () => {
    if (!preferences) return
    setAiLoading(true)
    const result = await fetchAiRemedies(
      latestScan?.acne_type ?? null,
      effectiveSkinType,
      provider,
    )
    if (result.length > 0) {
      setAiRemedies(result)
      setAiSource('ai')
    } else {
      setAiRemedies(null)
      setAiSource('static')
    }
    setAiLoading(false)
  }, [latestScan, effectiveSkinType, provider, preferences])

  useEffect(() => {
    if (!loading && preferences) fetchRemedies()
  }, [loading, preferences, fetchRemedies])

  const displayedRemedies: HomeRemedy[] = aiRemedies
    ?? (latestScan && preferences ? getHomeRemedies(latestScan, effectiveSkinType) : [])

  if (loading || !user || !preferences) {
    return (
      <main className="page-shell auth-shell">
        <div className="skeleton skeleton-title" style={{ width: '180px' }} />
      </main>
    )
  }

  return (
    <AppShell eyebrow="Comfort care" title="Remedies">
      <section className="feature-section">
        <div className="section-heading-row">
          <div>
            <div className="section-label">Home remedies</div>
            <h2 className="section-title">AI-generated suggestions by acne type</h2>
            <p className="muted-copy" style={{ maxWidth: '600px', marginTop: '0.4rem' }}>
              {aiSource === 'ai'
                ? `Live remedies generated by AI for ${effectiveSkinType} skin and ${latestScan?.acne_type?.replace(/_/g, ' ') ?? 'your skin'}.`
                : 'These are supportive home-care ideas, not a substitute for clinical treatment.'}
              {' '}Current filter: <strong style={{ color: 'var(--text)' }}>{effectiveSkinType}</strong>.
            </p>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.6rem', alignItems: 'flex-end' }}>
            {aiSource === 'ai' && (
              <span className="mini-badge accent" style={{ display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                <Bot size={11} /> AI-generated
              </span>
            )}

            <div style={{ display: 'flex', gap: '0.6rem', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
              <label className="field-stack" style={{ minWidth: '160px' }}>
                <span className="field-label">Filter by skin type</span>
                <select
                  className="text-select"
                  value={skinTypeOverride}
                  onChange={(e) => setSkinTypeOverride(e.target.value as SkinType | 'current')}
                >
                  <option value="current">My skin type ({preferences.skinType})</option>
                  {SKIN_TYPES.map((type) => (
                    <option key={type} value={type}>{type.charAt(0).toUpperCase() + type.slice(1)}</option>
                  ))}
                </select>
              </label>

              <label className="field-stack" style={{ minWidth: '140px' }}>
                <span className="field-label">AI provider</span>
                <select className="text-select" value={provider} onChange={(e) => setProvider(e.target.value as AIProvider)}>
                  {AI_PROVIDERS.map((p) => (
                    <option key={p.value} value={p.value}>{p.label}</option>
                  ))}
                </select>
              </label>

              <div className="field-stack" style={{ justifyContent: 'flex-end' }}>
                <span className="field-label">&nbsp;</span>
                <button
                  type="button"
                  className="button-secondary"
                  onClick={fetchRemedies}
                  disabled={aiLoading}
                  style={{ minHeight: '38px' }}
                >
                  <RefreshCw size={14} style={aiLoading ? { animation: 'spin 1s linear infinite' } : undefined} />
                  <span>{aiLoading ? 'Generating…' : 'Regenerate'}</span>
                </button>
              </div>
            </div>
          </div>
        </div>

        {aiLoading ? (
          <div className="stack" style={{ gap: '1.2rem' }}>
            {[1, 2, 3].map((i) => (
              <div key={i} className="skeleton" style={{ height: '220px', borderRadius: '12px' }} />
            ))}
          </div>
        ) : (
          <RemedyCards remedies={displayedRemedies} />
        )}
      </section>
    </AppShell>
  )
}
